### PR TITLE
Fix the way binary files are handled

### LINKED ISSUE #1: Plugin breakes images
When I'm trying to transfer folder with png image it gets corruped. File size changes and browser can't display it.

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes #1 

The problem is that `dir.files` reads everything as if they are a string, so `content` ends up being a string interpretation of a binary file.

### CODE REVIEW

**Comment by dkokorev90** [comment]
thanks!

**Comment by AsaAyers** [comment]
I see you tagged `0.1.3`. Is npm being slow to show the new version?

**Comment by dkokorev90** [comment]
i have just published it

**Comment by AsaAyers** [comment]
Thanks :) :clap:

**Pull request merged**
